### PR TITLE
Change Frontend groups for TG-CHE200122 to look at ap40 instead of login04

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Review by brianhlin — APPROVED** [review]
LGTM

**Comment by matyasselmeci** [comment]
Thanks, Brian! I'd like to have Mats check it too before merging.

**Comment by jasoncpatton** [comment]
FWIW, LGTM too. I've been replacing `DN` values with `"not_applicable"` in the other FEs following what moate(?) did for the (f.k.a.) GLOW FE.

**Review by rynge — APPROVED** [review]
LGTM, but is the project switching to use annex?

**Comment by matyasselmeci** [comment]
That's the eventual plan but Annex isn't quite ready yet -- this is our TODO list so far: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1055

**Pull request merged**
