### PR TITLE
Add RPM packaging from SVN

### PR DESCRIPTION
**Pull request by brianhlin**
Here's the RPM packaging that we currently have in SVN! We should be able to build from this as long as you tag versions so we can reference a sha

### CODE REVIEW

**Comment by djw8605** [comment]
Why is there a Gratia ProbeConfig in here?  I'm not really sure how it is every read.

**Comment by brianhlin** [comment]
@djw8605 atm, we tell folks to manually copy it over in the setup here https://opensciencegrid.org/docs/submit/osg-flock/#configuring-reporting-via-gratia

**Comment by djw8605** [comment]
Ah, interesting...  Ok.

**Comment by rynge** [comment]
Any suggestions on how to improve this would be welcome. We would like this to be as easy as possible. The Gratia probe is a common thing to misconfigure when installing this flocking hosts.

**Comment by brianhlin** [comment]
We could provide steps 4 and 5 by default by 2 and 3 would probably require some software machinery

**Pull request merged**
