### PR TITLE
First version of finding nearest cache

### PR DESCRIPTION
**Pull request by efajardo**

### CODE REVIEW

**Comment by efajardo** [comment]
@rynge and @drDaveD let me know what you think. I want to make this more modular so I can add it to LIGO and CMS. For LIGO I plan to pass it:

`attr -qg external_host /cvmfs/ligo.osgstorage.org| sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/'`

and for cms just let it fail with:
`attr -qg external_host /cvmfs/cms.cern.ch`

And use the curl to find the nearest Xcache. And CMS will just overwrite the list

**Comment by DrDaveD** [comment]
No no, I do not want to have yet another tool that encodes the list of stashcache servers and I definitely do not want a non-cvmfs client using the geo api on oasis-replica.  This should be based on the `stashcp --closest` command which already encodes the list of servers and uses the wlcg-wpad servers for geo api.

**Comment by DrDaveD** [comment]
Or if you can depend on cvmfs being there, then the attr commands you suggest are even better.

**Comment by DrDaveD** [comment]
And now I notice that the code you're replacing is already using stashcp --closest, so why remove that?

**Comment by efajardo** [comment]
@DrDaveD. Cause I want something that I can move to different frontends and pass different list of caches. Stashcp uses a fixed caches.json with the geo infromation hard coded and it takes several years for new information to get there. While frontend admins can udpate list of caches in a heartbeat.

**Comment by efajardo** [comment]
@DrDaveD I do not see a problem if I use a curl or `stashcp`. Stashcp won't work for CMS caches since they have nothign to do wit hCVMFS so I want to do something that works for everybody. Even people tat do not run on glideins (NANOAOD) and use caches.

**Comment by efajardo** [comment]
@DrDaveD I do not want to use stashcp since it gives pretty inaccurate results since it has its own list of caches. And I cannot maintain one for CMS one for LIGO and so on. I would really do not like to dpened on stashcp

**Comment by DrDaveD** [comment]
Let's fix the problems with the existing tool rather than inventing yet another one to maintain & get out of date.  I see that stashcp's caches.json contains longitude & latitude, but they are not referred to inside of the python code so they don't need to be there; they use the cvmfs geo api on wlcg-wpad servers.  We have a longstanding [OSG ticket](https://opensciencegrid.atlassian.net/browse/SOFTWARE-3516) that calls for having stashcp auto-discover the list of stashcaches.  If you still really want to allow a VO to override & maintain their own list, then let's add an option to stashcp to specify the list.  Please, no new separate tool.

**Comment by DrDaveD** [comment]
Adding @brianhlin @bbockelm @djw8605

**Comment by brianhlin** [comment]
>  If you still really want to allow a VO to override & maintain their own list, then let's add an option to stashcp to specify the list. Please, no new separate tool.

This seems reasonable to me

**Comment by efajardo** [comment]
@rynge I re did to make it more modular. Let me know what you think.

@DrDaveD I removed the fix list and we will rely on `stashcp --closest` as a failover.

**Comment by rynge** [comment]
I don't have much input to give as I don't know the usecase. As long as your are not breaking other functionality, please go ahead.

**Pull request merged**
