### PR TITLE
Update pilot tests for IGWN O4 CVMFS repos

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR updates the list of IGWN GWF files used to assert `HAS_LIGO_FRAMES` and adds separate pilot tests for all of the new IGWN CVMFS data repositories.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
cc @jasoncpatton

**Comment by duncanmmacleod** [comment]
I would like to update the cvmfs check script so that it checks _all_ of the files listed in the `frames_files_small.txt` file, rather than a random single file. WIP.

**Comment by duncanmmacleod** [comment]
@jasoncpatton et al (not sure who actually will review/test this), I have attempted to 'upgrade' the tests as follows.

- rename the test script `ligo-cvmfs-storage-check.sh` -> `igwn-cvmfs-storage-check.sh`
- rename the `frame_files_small.txt` -> `igwn-cvmfs-data.txt`
- reformat the data file to be `CVMFS_ATTR /path/to/file` to test and advertise each repo separately
- internally loop over all of the lines in the data file, rather than picking one at random, and aggregate the results of all tests

I hope that's not overreaching and created a bunch of work on OSG to integrate.

**Comment by jasoncpatton** [comment]
@rynge This LGTM. I don't think the IGWN FE picks up changes from `osg-flock` automatically, so merging https://github.com/opensciencegrid/tiger-osg-config/pull/818 can come after.

**Pull request merged**
